FROM jenkins/jenkins 
USER root 
RUN apt-get update && apt-get install -y lsb-release 
RUN apt-get update && apt-get install -y --no-install-recommends \
binutils ca-certificates curl git python3 python3-venv python3-pip python3-setuptools python3-wheel python3-dev wget \
&& rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/python3 /usr/bin/python
# Crea el entorno virtual y activa el script de activación
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install docker-py feedparser nosexcover prometheus_client pycobertura pylint pytest pytest-cov requests setuptools sphinx pyinstaller
RUN echo "PATH=${PATH}" >> /etc/environment
# Instala PyInstaller dentro del entorno virtual
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \ 
    https://download.docker.com/linux/debian/gpg 
RUN echo "deb [arch=$(dpkg --print-architecture) \ 
    signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \ 
    https://download.docker.com/linux/debian \ 
    $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list 
RUN apt-get update && apt-get install -y docker-ce-cli 
USER jenkins 
RUN jenkins-plugin-cli --plugins "blueocean docker-workflow"
